/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
    //jcenter()
    //mavenLocal()
    maven {
        url = uri("https://download.eclipse.org/releases/2024-06")
    }

    maven {
        url = uri("https://download.eclipse.org/tools/orbit/simrel/maven-osgi/release/4.32.0")
    }
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "com.archimatetool"
version = "5.2.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
